import os
import subprocess
import sys

import pytest
import httpx


BACKEND_URL = os.environ.get("BACKEND_URL", "http://backend:3000")
MCP_URL = os.environ.get("MCP_URL", "http://mcp-server:8080")
WEBUI_DB_PATH = os.environ.get("WEBUI_DB_PATH", "")


@pytest.fixture(scope="session", autouse=True)
def ingest_conversations():
    """Ingest Open WebUI conversations once before all tests.

    Only runs when WEBUI_DB_PATH is set and the file exists.
    """
    if not WEBUI_DB_PATH or not os.path.isfile(WEBUI_DB_PATH):
        yield
        return

    script = os.path.join(os.path.dirname(__file__), "ingest_webui.py")
    if not os.path.isfile(script):
        print(f"Ingestion script not found at {script}, skipping ingestion")
        yield
        return

    print(f"\n=== Ingesting conversations from {WEBUI_DB_PATH} ===")
    result = subprocess.run(
        [
            sys.executable, script,
            "--db", WEBUI_DB_PATH,
            "--backend-url", BACKEND_URL,
        ],
        capture_output=True,
        text=True,
        timeout=600,
    )
    print(result.stdout)
    if result.returncode != 0:
        print(f"Ingestion stderr: {result.stderr}", file=sys.stderr)
        pytest.fail(f"Ingestion failed with exit code {result.returncode}")

    yield


@pytest.fixture
def backend_url():
    return BACKEND_URL


@pytest.fixture
def mcp_url():
    return MCP_URL


@pytest.fixture
async def backend_client(backend_url):
    async with httpx.AsyncClient(base_url=backend_url) as client:
        yield client


@pytest.fixture(autouse=True)
async def clean_memories(backend_url):
    """Each test uses unique content/tags to avoid collisions.

    The backend uses PostgreSQL with pgvector in Docker — there is no
    reset API, so tests rely on unique prefixes generated by unique().
    """
    yield
