# Generated by Django 5.2.1 on 2025-06-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_endpoint_url', models.URLField(default='http://localhost:11434')),
                ('extraction_model', models.CharField(default='llama2', max_length=200)),
                ('extraction_provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('openai_compatible', 'OpenAI Compatible'), ('ollama', 'Ollama')], default='ollama', max_length=20)),
                ('embeddings_endpoint_url', models.URLField(default='http://localhost:11434')),
                ('embeddings_model', models.CharField(default='nomic-embed-text', max_length=200)),
                ('embeddings_provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('openai_compatible', 'OpenAI Compatible'), ('ollama', 'Ollama')], default='ollama', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Settings',
                'verbose_name_plural': 'LLM Settings',
            },
        ),
    ]
