# Generated by Django 5.2.1 on 2025-06-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmsettings',
            name='embeddings_model',
            field=models.CharField(default='mxbai-embed-large', max_length=200),
        ),
        migrations.AlterField(
            model_name='llmsettings',
            name='extraction_model',
            field=models.CharField(default='llama3', max_length=200),
        ),
    ]
