# Generated by Django 5.2.1 on 2025-06-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_llmsettings_memory_extraction_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmsettings',
            name='embeddings_endpoint_api_key',
            field=models.CharField(blank=True, default='none', null=True),
        ),
        migrations.AddField(
            model_name='llmsettings',
            name='embeddings_timeout',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='llmsettings',
            name='extraction_endpoint_api_key',
            field=models.CharField(blank=True, default='none', null=True),
        ),
        migrations.AddField(
            model_name='llmsettings',
            name='extraction_timeout',
            field=models.IntegerField(default=30),
        ),
    ]
