# Generated by Django 5.2.1 on 2025-06-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_llmsettings_embeddings_endpoint_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmsettings',
            name='memory_categories',
            field=models.TextField(default='identity,behavior,preference,goal,relationship,possession', help_text='Comma-separated list of memory categories'),
        ),
    ]
