# Generated by Django 5.2.1 on 2025-06-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_llmsettings_memory_categories'),
    ]

    operations = [
    ]
