# Generated by Django 5.2.1 on 2025-06-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_alter_llmsettings_memory_extraction_prompt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmsettings',
            name='memory_categories',
        ),
        migrations.AlterField(
            model_name='llmsettings',
            name='memory_search_prompt',
            field=models.TextField(default='You are an intelligent memory search system. Generate search queries that capture both direct and indirect connections to find relevant user memories.\n\n**OUTPUT REQUIREMENT:**\nRespond with ONLY a JSON array: `[{"search_query": "...", "confidence": float, "search_type": "...", "rationale": "..."}]`\n\n**SEARCH STRATEGY:**\n1. **Direct queries**: Explicit matches for the user\'s request\n2. **Semantic queries**: Related concepts and broader themes  \n3. **Contextual queries**: Situations where this topic might be relevant\n4. **Experience queries**: Past experiences that inform preferences\n5. **Interest queries**: General interests that connect to the request\n\n**SEARCH TYPES:**\n- "direct": Explicit match to request\n- "semantic": Related concepts/themes\n- "experiential": Past experiences that inform preferences\n- "contextual": Situational relevance\n- "interest": General interests that connect\n\n**JSON STRUCTURE:**\n- **search_query**: The query to find relevant memories\n- **confidence**: 0.0-1.0 confidence score for relevance\n- **search_type**: Type of search (direct, semantic, experiential, contextual, interest)\n- **rationale**: Explanation of why this query is relevant\n\n**EXAMPLES:**\n\nUser asks: "Help me create a playlist"\n```json\n[\n  {"search_query": "user\'s favorite music", "confidence": 1.0, "search_type": "direct", "rationale": "Direct musical preferences"},\n  {"search_query": "user\'s favorite artists", "confidence": 1.0, "search_type": "direct", "rationale": "Specific artist preferences"},\n  {"search_query": "concerts user attended", "confidence": 0.8, "search_type": "experiential", "rationale": "Live music experiences show preferences"},\n  {"search_query": "music user loved", "confidence": 0.9, "search_type": "semantic", "rationale": "Any music they expressed enjoying"},\n  {"search_query": "festivals user went to", "confidence": 0.7, "search_type": "experiential", "rationale": "Festival experiences reveal music taste"},\n  {"search_query": "songs user mentioned", "confidence": 0.8, "search_type": "semantic", "rationale": "Any songs they\'ve referenced"},\n  {"search_query": "user\'s mood preferences", "confidence": 0.6, "search_type": "contextual", "rationale": "Mood affects playlist preferences"}\n]\n```\n\nUser asks: "Recommend some books"\n```json\n[\n  {"search_query": "books user read", "confidence": 1.0, "search_type": "direct", "rationale": "Reading history shows preferences"},\n  {"search_query": "user\'s academic interests", "confidence": 0.8, "search_type": "semantic", "rationale": "Academic interests suggest book topics"},\n  {"search_query": "subjects user is fascinated by", "confidence": 0.9, "search_type": "semantic", "rationale": "Fascination indicates reading interest"},\n  {"search_query": "user\'s hobbies", "confidence": 0.7, "search_type": "contextual", "rationale": "Hobbies suggest relevant book topics"},\n  {"search_query": "topics user wants to learn", "confidence": 0.8, "search_type": "semantic", "rationale": "Learning goals indicate book interests"},\n  {"search_query": "user\'s professional field", "confidence": 0.6, "search_type": "contextual", "rationale": "Career suggests relevant reading"},\n  {"search_query": "sciences user mentioned", "confidence": 0.7, "search_type": "semantic", "rationale": "Scientific interests suggest book topics"}\n]\n```\n\nGenerate comprehensive search queries that find both obvious and subtle connections.'),
        ),
    ]
