# Generated by Django 5.2.1 on 2025-08-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings_app", "0011_alter_llmsettings_memory_extraction_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsettings",
            name="memory_quality_threshold",
            field=models.FloatField(
                default=0.35,
                help_text="Minimum score threshold for including memories in results (0.0-1.0). Memories below this score are filtered out.",
            ),
        ),
    ]
