# Generated by Django 5.2.1 on 2025-08-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0012_add_consolidation_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsettings",
            name="enable_graph_enhanced_retrieval",
            field=models.BooleanField(
                default=False, help_text="Enable graph-enhanced memory retrieval"
            ),
        ),
        migrations.AddField(
            model_name="llmsettings",
            name="graph_build_status",
            field=models.CharField(
                choices=[
                    ("not_built", "Not Built"),
                    ("building", "Building"),
                    ("built", "Built"),
                    ("failed", "Failed"),
                    ("outdated", "Outdated"),
                ],
                default="not_built",
                help_text="Current graph build status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="llmsettings",
            name="graph_last_build",
            field=models.DateTimeField(
                blank=True, help_text="Last successful graph build timestamp", null=True
            ),
        ),
    ]
