# Generated by Django 5.2.1 on 2025-08-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0013_llmsettings_enable_graph_enhanced_retrieval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmsettings",
            name="graph_build_status",
            field=models.CharField(
                choices=[
                    ("not_built", "Not Built"),
                    ("building", "Building"),
                    ("built", "Built"),
                    ("failed", "Failed"),
                    ("outdated", "Outdated"),
                    ("partial", "Partial"),
                ],
                default="not_built",
                help_text="Current graph build status",
                max_length=20,
            ),
        ),
    ]
