# Generated by Django 5.2.1 on 2025-10-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0013_alter_llmsettings_memory_extraction_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsettings",
            name="max_import_file_size_mb",
            field=models.IntegerField(
                default=500,
                help_text="Maximum file size for Open WebUI database imports (in MB)",
            ),
        ),
    ]
