# Generated by Django 5.0 on 2025-01-07 (Phase 1 initial migration)

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('turn_number', models.IntegerField()),
                ('user_message', models.TextField()),
                ('assistant_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vector_id', models.CharField(max_length=255, unique=True)),
                ('extracted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['user_id', '-timestamp'], name='memories_co_user_id_4e8a8c_idx'),
                    models.Index(fields=['session_id', 'turn_number'], name='memories_co_session_b9f3a0_idx'),
                ],
                'unique_together': {('session_id', 'turn_number')},
            },
        ),
    ]
