# Generated by Django 5.2.1 on 2025-06-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='embedding',
        ),
        migrations.AddField(
            model_name='memory',
            name='vector_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['vector_id'], name='memories_me_vector__444a11_idx'),
        ),
    ]
