# Generated by Django 5.2.1 on 2025-06-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_remove_memory_embedding_memory_vector_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='connections',
            field=models.JSONField(default=list, help_text='Broader topics this memory relates to'),
        ),
        migrations.AddField(
            model_name='memory',
            name='context',
            field=models.TextField(blank=True, help_text='Context where this memory was mentioned'),
        ),
        migrations.AddField(
            model_name='memory',
            name='search_tags',
            field=models.JSONField(default=list, help_text='Searchable tags for this memory'),
        ),
    ]
