# Generated by Django 5.2.1 on 2025-11-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_add_settings_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversationturn',
            new_name='memories_co_user_id_7f2a82_idx',
            old_name='memories_co_user_id_4e8a8c_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationturn',
            new_name='memories_co_session_4890e0_idx',
            old_name='memories_co_session_b9f3a0_idx',
        ),
    ]
