# Generated by Django 5.2.1 on 2025-08-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0003_memory_connections_memory_context_memory_search_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="fact_type",
            field=models.CharField(
                choices=[
                    ("mutable", "Mutable"),
                    ("immutable", "Immutable"),
                    ("temporal", "Temporal"),
                ],
                default="mutable",
                help_text="Type of fact - whether it can change over time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this memory is currently active (not superseded)",
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="last_validated",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time this memory was validated or confirmed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="original_confidence",
            field=models.FloatField(
                default=0.5,
                help_text="Original confidence score when memory was created",
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                help_text="Memory that this one replaces/updates",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="superseded_by",
                to="memories.memory",
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="temporal_confidence",
            field=models.FloatField(
                default=0.5, help_text="Current confidence after temporal decay"
            ),
        ),
        migrations.AddIndex(
            model_name="memory",
            index=models.Index(
                fields=["user_id", "is_active"], name="memories_me_user_id_90af34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memory",
            index=models.Index(
                fields=["fact_type", "is_active"], name="memories_me_fact_ty_8c57f4_idx"
            ),
        ),
    ]
