# Generated by Django 5.2.1 on 2025-08-12 05:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0004_add_conflict_resolution_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                (
                    "content",
                    models.TextField(help_text="Original conversation text chunk"),
                ),
                (
                    "vector_id",
                    models.CharField(
                        help_text="Vector database ID for this chunk's embedding",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="When this conversation segment occurred"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context: source info, session data, etc.",
                    ),
                ),
                (
                    "extracted_memory_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of Memory IDs that were extracted from this chunk",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RemoveIndex(
            model_name="memory",
            name="memories_me_vector__444a11_idx",
        ),
        migrations.RemoveField(
            model_name="memory",
            name="connections",
        ),
        migrations.RemoveField(
            model_name="memory",
            name="context",
        ),
        migrations.RemoveField(
            model_name="memory",
            name="search_tags",
        ),
        migrations.RemoveField(
            model_name="memory",
            name="vector_id",
        ),
        migrations.AddField(
            model_name="memory",
            name="conversation_chunk_ids",
            field=models.JSONField(
                default=list,
                help_text="List of ConversationChunk IDs that led to this memory extraction",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationchunk",
            index=models.Index(
                fields=["user_id"], name="memories_co_user_id_6d9a7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationchunk",
            index=models.Index(
                fields=["timestamp"], name="memories_co_timesta_de55fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationchunk",
            index=models.Index(
                fields=["vector_id"], name="memories_co_vector__6185c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationchunk",
            index=models.Index(
                fields=["user_id", "timestamp"], name="memories_co_user_id_fbea25_idx"
            ),
        ),
    ]
