# Generated by Django 5.2.1 on 2025-11-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0006_add_prompt_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='enable_multipass_extraction',
            field=models.BooleanField(default=True, help_text='Enable multi-pass extraction for higher recall (Pass 1: explicit facts, Pass 2: implied/contextual facts)'),
        ),
    ]
