# Generated by Django 5.2.1 on 2025-11-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0010_add_amem_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='generation_top_p',
            field=models.FloatField(default=0.8, help_text='Top-p (nucleus) sampling for generation (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='generation_top_k',
            field=models.IntegerField(default=20, help_text='Top-k sampling for generation (0 = disabled)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='generation_min_p',
            field=models.FloatField(default=0.0, help_text='Min-p sampling for generation (0.0-1.0)'),
        ),
    ]
