# Generated by Django 5.2.1 on 2025-11-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0011_add_generation_sampling_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicnote',
            name='contextual_description',
            field=models.TextField(blank=True, help_text='A-MEM contextual description (Xi) - richer context for the note'),
        ),
        migrations.AddField(
            model_name='atomicnote',
            name='is_amem_enriched',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this note has been enriched with A-MEM metadata'),
        ),
        migrations.AddField(
            model_name='atomicnote',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='A-MEM keywords (Ki) - key concepts extracted from the note'),
        ),
        migrations.AddField(
            model_name='atomicnote',
            name='llm_tags',
            field=models.JSONField(blank=True, default=list, help_text='A-MEM tags (Gi) - broad categories for classification'),
        ),
        migrations.AlterField(
            model_name='conversationturn',
            name='vector_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='enable_query_expansion',
            field=models.BooleanField(default=False, help_text='Enable query expansion (may be redundant with A-MEM multi-attribute embeddings - test both)'),
        ),
    ]
