# Generated by Django 5.2.1 on 2025-11-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0012_atomicnote_contextual_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomicnote',
            name='contextual_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='atomicnote',
            name='is_amem_enriched',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='atomicnote',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='atomicnote',
            name='llm_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
